# Generated by Django 5.1.2 on 2024-10-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.IntegerField()),
                ('a_name', models.CharField(max_length=50)),
                ('a_email', models.EmailField(max_length=254)),
                ('a_contact', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
