# Generated by Django 5.1.2 on 2024-10-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='a_address',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
